In [15]:
import pandas as pd 
import matplotlib.pyplot as plt 
df = pd.read_csv("datasets/manipulation/1.csv")
df.head()

,Unnamed: 0,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,0,13328,1399,1,1,2010,1,1,1,3.5,186005,6.0,1,1,1,1,1,12
1,1,16621,1018,2,2,2011,1,0,2,3.0,192000,6.0,2,1,1,1,2,8
2,2,8467,-,3,3,2006,2,0,2,1.3,200000,4.0,3,2,1,2,2,2
3,3,3607,862,4,4,2011,1,1,1,2.5,168966,4.0,1,1,1,1,3,0
4,4,11726,446,3,3,2014,2,1,2,1.3,91901,4.0,1,2,1,1,1,4

## Process Levy so its used aswell
=> Replace "-" with 0

In [ ]:
levy_mapping = {"-":0}
df.replace(levy_mapping,inplace=True)
df.head()

object

In [6]:
df["Levy"] = pd.to_numeric(df["Levy"],errors="coerce")
df["Levy"].dtype
df.describe()

,Unnamed: 0,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
count,17306.000000,1.730600e+04,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,1.730600e+04,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000,17306.000000
mean,9608.325263,1.744961e+04,674.369352,8.010863,143.896279,2011.056974,2.636889,0.740899,2.251647,2.376667,1.556669e+06,4.568242,1.431816,1.895585,1.043569,1.080088,3.288917,6.493702
std,5554.610524,2.006192e+05,574.680978,6.889905,262.065702,5.636826,1.685642,0.438154,1.137399,6.174598,4.834610e+07,1.175546,0.876152,0.538939,0.227437,0.271437,2.531779,4.328332
min,0.000000,1.000000e+00,0.000000,1.000000,1.000000,1939.000000,1.000000,0.000000,1.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,4806.250000,4.547000e+03,0.000000,5.000000,8.000000,2010.000000,1.000000,0.000000,2.000000,1.800000,7.099400e+04,4.000000,1.000000,2.000000,1.000000,1.000000,2.000000,4.000000
50%,9573.500000,1.227650e+04,751.000000,6.000000,40.000000,2012.000000,3.000000,1.000000,2.000000,2.000000,1.260000e+05,4.000000,1.000000,2.000000,1.000000,1.000000,3.000000,4.000000
75%,14408.750000,2.110300e+04,1017.000000,8.000000,151.000000,2015.000000,3.000000,1.000000,3.000000,2.500000,1.881940e+05,4.000000,1.000000,2.000000,1.000000,1.000000,4.000000,12.000000
max,19236.000000,2.630750e+07,11714.000000,65.000000,1590.000000,2020.000000,11.000000,1.000000,7.000000,571.000000,2.147484e+09,16.000000,4.000000,3.000000,3.000000,2.000000,16.000000,16.000000

In [14]:
print(len(df.columns))
print(df.columns)
df.drop(columns=["Unnamed: 0"],inplace=True)
df.to_csv("datasets/manipulation/2.csv")

17
Index(['Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year', 'Category',
       'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

KeyError: "['Unnamed: 0'] not found in axis"